# generated by datamodel-codegen:
#   filename:  cat_schema.json
#   timestamp: 2023-07-02T07:37:43+00:00

# developers comment: seems faster and easer to write this myself.
#  Perhaps works best if many are going to use my API, 
#  as part of the documentation of the API.

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra, Field


class Address(BaseModel):
    class Config:
        extra = Extra.forbid

    city: Optional[str] = Field(None, description="Cat's city")
    zip_code: Optional[str] = Field(None, description='Postal code')
    number: Optional[int] = Field(None, description='House number')


class CatRequest(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str = Field(..., description="Cat's name.")
    age: Optional[int] = Field(None, description="Cat's age, in cat years.")
    address: Optional[Address] = Field(None, description='Where does the cat live.')
